//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrabIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOOKUPCATEGORY
    {
        public LOOKUPCATEGORY()
        {
            this.GLOBALLOOKUPs = new HashSet<GLOBALLOOKUP>();
        }
    
        public int LookupCatID { get; set; }
        public string LookupCatDesc { get; set; }
    
        public virtual ICollection<GLOBALLOOKUP> GLOBALLOOKUPs { get; set; }
    }
}
