//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrabIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEASUREMENTLINK
    {
        public int ProcessTypeID { get; set; }
        public int MeasurementTypeID { get; set; }
        public Nullable<double> LowerLimit { get; set; }
        public Nullable<double> UpperLimit { get; set; }
    
        public virtual MEASUREMENTTYPE MEASUREMENTTYPE { get; set; }
        public virtual PROCESSTYPE PROCESSTYPE { get; set; }
    }
}
