//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrabIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESS
    {
        public PROCESS()
        {
            this.MEASUREMENTS = new HashSet<MEASUREMENT>();
        }
    
        public int ProcessID { get; set; }
        public int ShiftTypeID { get; set; }
        public System.DateTime Date { get; set; }
        public string StartTime { get; set; }
        public string EndTime { get; set; }
        public int ProcessTypeID { get; set; }
        public int UserID { get; set; }
    
        public virtual ICollection<MEASUREMENT> MEASUREMENTS { get; set; }
        public virtual PROCESSTYPE PROCESSTYPE { get; set; }
        public virtual SHIFTTYPE SHIFTTYPE { get; set; }
        public virtual USER USER { get; set; }
    }
}
