//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrabIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESSCATEGORy
    {
        public PROCESSCATEGORy()
        {
            this.PROCESSTYPES = new HashSet<PROCESSTYPE>();
            this.PROCESSTYPES1 = new HashSet<PROCESSTYPE>();
        }
    
        public int ProcessCategoryID { get; set; }
        public string Desc { get; set; }
    
        public virtual ICollection<PROCESSTYPE> PROCESSTYPES { get; set; }
        public virtual ICollection<PROCESSTYPE> PROCESSTYPES1 { get; set; }
    }
}
