//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrabIt.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROCESSTYPE
    {
        public PROCESSTYPE()
        {
            this.MEASUREMENTLINKs = new HashSet<MEASUREMENTLINK>();
            this.MEASUREMENTTYPES = new HashSet<MEASUREMENTTYPE>();
            this.PROCESSES = new HashSet<PROCESS>();
            this.PROCESSCATEGORIES = new HashSet<PROCESSCATEGORy>();
        }
    
        public int ProcessTypeID { get; set; }
        public string Desc { get; set; }
        public int ProcessCategoryID { get; set; }
    
        public virtual ICollection<MEASUREMENTLINK> MEASUREMENTLINKs { get; set; }
        public virtual ICollection<MEASUREMENTTYPE> MEASUREMENTTYPES { get; set; }
        public virtual PROCESSCATEGORy PROCESSCATEGORy { get; set; }
        public virtual ICollection<PROCESS> PROCESSES { get; set; }
        public virtual ICollection<PROCESSCATEGORy> PROCESSCATEGORIES { get; set; }
    }
}
